#!/usr/bin/env ruby
# Renders the static site into public/ from data/*.yml|json + templates/*.erb.
# No Rails, no gems beyond the Ruby standard library.

require "erb"
require "yaml"
require "json"
require "fileutils"
require "cgi"
require "rbconfig"

ROOT = File.expand_path(__dir__)
DATA_DIR = File.join(ROOT, "data")
TEMPLATES_DIR = File.join(ROOT, "templates")
ASSETS_DIR = File.join(ROOT, "assets")
OUT_DIR = File.join(ROOT, "public")

# GitHub Pages serves project sites (not <user>.github.io) at /<repo-name>/.
# Set to "" if this ever moves to a custom domain or a <user>.github.io repo.
BASE_PATH = "/redgate_handbook"

LOCALES = %w[en de]
PRODUCT_KEYS = [:monitor, :flyway, :toolbelt_essentials]

def deep_symbolize(obj)
  case obj
  when Hash
    obj.each_with_object({}) { |(k, v), h| h[k.to_sym] = deep_symbolize(v) }
  when Array
    obj.map { |v| deep_symbolize(v) }
  else
    obj
  end
end

def page_path(locale, page)
  prefix = locale == "en" ? "" : "/#{locale}"
  page == :home ? "#{BASE_PATH}#{prefix}/" : "#{BASE_PATH}#{prefix}/products/#{page}/"
end

# Minimal render context: exposes locals as bare methods/ivars inside ERB,
# plus a couple of view helpers that mirror what the old Rails views used.
class RenderContext
  def initialize(locals)
    locals.each { |k, v| instance_variable_set("@#{k}", v) }
    @__locals = locals
  end

  def method_missing(name, *args)
    return @__locals[name] if @__locals.key?(name)
    super
  end

  def respond_to_missing?(name, include_private = false)
    @__locals.key?(name) || super
  end

  def h(str)
    CGI.escapeHTML(str.to_s)
  end

  def present?(value)
    case value
    when nil then false
    when String then !value.strip.empty?
    when Array, Hash then !value.empty?
    else true
    end
  end

  def asset(path)
    "#{BASE_PATH}#{path}"
  end

  # UI string lookup with %{placeholder} interpolation, e.g. t(:last_updated, date: "2026-06-16")
  def t(key, **interpolations)
    template = UI_STRINGS.fetch(@__locals.fetch(:locale).to_sym).fetch(key)
    interpolations.empty? ? template : (template % interpolations)
  end

  # Releases summaries are HTML generated by our own fetch script (data/releases_data.json),
  # not user input — still allowlist to <a href target> only, matching the old Rails `sanitize` call.
  def sanitize_summary(html)
    return "" if html.nil?

    html.to_s
        .gsub(/<(?!\/?a\b)[^>]*>/i, "")
        .gsub(/<a\s+([^>]*)>/i) do
          attrs = Regexp.last_match(1)
          href = attrs[/href\s*=\s*"([^"]*)"/i, 1]
          target = attrs[/target\s*=\s*"([^"]*)"/i, 1]
          tag = +"<a"
          tag << %( href="#{CGI.escapeHTML(href)}") if href
          tag << %( target="#{CGI.escapeHTML(target)}") if target
          tag << ">"
        end
  end

  def render(template_name)
    path = File.join(TEMPLATES_DIR, template_name)
    ERB.new(File.read(path), trim_mode: "<>").result(binding)
  end
end

def render_template(name, locals)
  RenderContext.new(locals).render(name)
end

def wrap_in_layout(inner_html, locale:, product:)
  nav_links = [["Monitor", :monitor], ["Flyway", :flyway], ["Toolbelt Essentials", :toolbelt_essentials]]
    .map { |label, key| [label, page_path(locale, key), product == key.to_s] }

  lang_links = LOCALES.to_h { |l| [l, page_path(l, product ? product.to_sym : :home)] }

  render_template("layout.html.erb",
    content: inner_html,
    locale: locale,
    product: product,
    home_url: page_path(locale, :home),
    nav_links: nav_links,
    lang_links: lang_links)
end

UI_STRINGS = deep_symbolize(YAML.load_file(File.join(DATA_DIR, "ui_strings.yml")))

PRODUCTS = LOCALES.to_h do |locale|
  [locale, deep_symbolize(YAML.load_file(File.join(DATA_DIR, "products.#{locale}.yml")))]
end

releases_path = File.join(DATA_DIR, "releases_data.json")
RELEASES = File.exist?(releases_path) ? deep_symbolize(JSON.parse(File.read(releases_path))) : {}

unless system(RbConfig.ruby, File.join(ROOT, "build_css.rb"))
  warn "Tailwind rebuild failed or skipped — reusing existing assets/css/tailwind.css"
end

FileUtils.rm_rf(OUT_DIR)
FileUtils.mkdir_p(OUT_DIR)

# Static assets (shared across locales — images/CSS/icons don't need translating)
FileUtils.cp_r(File.join(ASSETS_DIR, "images"), OUT_DIR)
FileUtils.mkdir_p(File.join(OUT_DIR, "css"))
FileUtils.cp(File.join(ASSETS_DIR, "css", "tailwind.css"), File.join(OUT_DIR, "css", "tailwind.css"))
%w[icon.svg robots.txt 404.html].each do |file|
  FileUtils.cp(File.join(ASSETS_DIR, file), File.join(OUT_DIR, file))
end

LOCALES.each do |locale|
  products = PRODUCTS.fetch(locale)

  # Home page
  home_html = render_template("home.html.erb", locale: locale, products: products)
  out_dir = locale == "en" ? OUT_DIR : File.join(OUT_DIR, locale)
  FileUtils.mkdir_p(out_dir)
  File.write(File.join(out_dir, "index.html"), wrap_in_layout(home_html, locale: locale, product: nil))

  # Product pages
  PRODUCT_KEYS.each do |key|
    content = products[key]
    unless content
      warn "No content for product '#{key}' in data/products.#{locale}.yml — skipping."
      next
    end

    releases = RELEASES.dig(key, locale.to_sym)
    product_html = render_template("product.html.erb", locale: locale, product_content: content, releases: releases)
    dir = File.join(out_dir, "products", key.to_s)
    FileUtils.mkdir_p(dir)
    File.write(File.join(dir, "index.html"), wrap_in_layout(product_html, locale: locale, product: key.to_s))
  end
end

puts "Generated static site into #{OUT_DIR}"
