#!/usr/bin/env ruby
# Renders the static site into public/ from data/*.yml|json + templates/*.erb.
# No Rails, no gems beyond the Ruby standard library.

require "erb"
require "yaml"
require "json"
require "fileutils"
require "cgi"

ROOT = File.expand_path(__dir__)
DATA_DIR = File.join(ROOT, "data")
TEMPLATES_DIR = File.join(ROOT, "templates")
ASSETS_DIR = File.join(ROOT, "assets")
OUT_DIR = File.join(ROOT, "public")

def deep_symbolize(obj)
  case obj
  when Hash
    obj.each_with_object({}) { |(k, v), h| h[k.to_sym] = deep_symbolize(v) }
  when Array
    obj.map { |v| deep_symbolize(v) }
  else
    obj
  end
end

# Minimal render context: exposes locals as bare methods/ivars inside ERB,
# plus a couple of view helpers that mirror what the old Rails views used.
class RenderContext
  def initialize(locals)
    locals.each { |k, v| instance_variable_set("@#{k}", v) }
    @__locals = locals
  end

  def method_missing(name, *args)
    return @__locals[name] if @__locals.key?(name)
    super
  end

  def respond_to_missing?(name, include_private = false)
    @__locals.key?(name) || super
  end

  def h(str)
    CGI.escapeHTML(str.to_s)
  end

  def present?(value)
    case value
    when nil then false
    when String then !value.strip.empty?
    when Array, Hash then !value.empty?
    else true
    end
  end

  # Releases summaries are HTML generated by our own fetch script (config/releases_data.json),
  # not user input — still allowlist to <a href target> only, matching the old Rails `sanitize` call.
  def sanitize_summary(html)
    return "" if html.nil?

    html.to_s
        .gsub(/<(?!\/?a\b)[^>]*>/i, "")
        .gsub(/<a\s+([^>]*)>/i) do
          attrs = Regexp.last_match(1)
          href = attrs[/href\s*=\s*"([^"]*)"/i, 1]
          target = attrs[/target\s*=\s*"([^"]*)"/i, 1]
          tag = +"<a"
          tag << %( href="#{CGI.escapeHTML(href)}") if href
          tag << %( target="#{CGI.escapeHTML(target)}") if target
          tag << ">"
        end
  end

  def render(template_name)
    path = File.join(TEMPLATES_DIR, template_name)
    ERB.new(File.read(path), trim_mode: "<>").result(binding)
  end
end

def render_template(name, locals)
  RenderContext.new(locals).render(name)
end

def wrap_in_layout(inner_html, product_key)
  render_template("layout.html.erb", content: inner_html, product: product_key)
end

products_data = deep_symbolize(YAML.load_file(File.join(DATA_DIR, "products.yml")))
PRODUCTS = products_data[:en][:products]

releases_path = File.join(DATA_DIR, "releases_data.json")
RELEASES = File.exist?(releases_path) ? deep_symbolize(JSON.parse(File.read(releases_path))) : {}

PRODUCT_KEYS = [:monitor, :flyway, :test_data_manager, :toolbelt_essentials]

FileUtils.rm_rf(OUT_DIR)
FileUtils.mkdir_p(OUT_DIR)

# Static assets
FileUtils.cp_r(File.join(ASSETS_DIR, "images"), OUT_DIR)
FileUtils.mkdir_p(File.join(OUT_DIR, "css"))
FileUtils.cp(File.join(ASSETS_DIR, "css", "tailwind.css"), File.join(OUT_DIR, "css", "tailwind.css"))
%w[icon.png icon.svg robots.txt 404.html].each do |file|
  FileUtils.cp(File.join(ASSETS_DIR, file), File.join(OUT_DIR, file))
end

# Home page
home_html = render_template("home.html.erb", products: PRODUCTS)
File.write(File.join(OUT_DIR, "index.html"), wrap_in_layout(home_html, nil))

# Product pages
PRODUCT_KEYS.each do |key|
  content = PRODUCTS[key]
  unless content
    warn "No content for product '#{key}' in data/products.yml — skipping."
    next
  end

  product_html = render_template("product.html.erb", product_content: content, releases: RELEASES[key])
  dir = File.join(OUT_DIR, "products", key.to_s)
  FileUtils.mkdir_p(dir)
  File.write(File.join(dir, "index.html"), wrap_in_layout(product_html, key.to_s))
end

puts "Generated static site into #{OUT_DIR}"
